name: .NET Build

on:
  push:
    branches: 
        - master
env:
  APP_NAME: "Assessment Tool Prototype.sln"
  PACKAGE_PATH: 'published'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild
      with:
        vs-version: "16.5"
    
    - name: Build .NET 4.8
      run: msbuild ${{ env.APP_NAME }} /p:Configuration=Release /p:DeployOnBuild=true /p:publishUrl=${{ env.PACKAGE_PATH }}
    
    - name: Upload .NET 4.8
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.APP_NAME }}
        path: NET Framwork48\bin\Release
