name: .NET Build

on:
  push:
    branches: 
        - master
env:
  APP_NAME: "Assessment Tool Prototype"
  APP_FULL_NAME: "Assessment Tool Prototype\\Assessment Tool Prototype.sln"
  APP_OUTPUT_FOLDER: "Assessment Tool Prototype\\NET Framwork48\bin\\Release"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: "16.5"
    
    - name: Build .NET 4.8
      run: msbuild "${{ env.APP_FULL_NAME }}" /p:Configuration=Release
    
    - name: Upload .NET 4.8
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.APP_NAME }}
        path: ${{ APP_OUTPUT_FOLDER }}
